// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlV12QTttOP-WWvd9cYos1uvaSdKe_-p0',
    appId: '1:995049274759:web:2947cbcd56dac7761f2722',
    messagingSenderId: '995049274759',
    projectId: 'fir-flutterdemo-458a6',
    authDomain: 'fir-flutterdemo-458a6.firebaseapp.com',
    storageBucket: 'fir-flutterdemo-458a6.appspot.com',
    measurementId: 'G-FYYRRT22JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuz-kNrF2bo_mlzfyxjNetF9ZfS7aD708',
    appId: '1:995049274759:android:cf21af918565e8581f2722',
    messagingSenderId: '995049274759',
    projectId: 'fir-flutterdemo-458a6',
    storageBucket: 'fir-flutterdemo-458a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRMiWNlkI4LOpryTH9ZptS1cTy1Jp3kA',
    appId: '1:995049274759:ios:cde547b15a0fbafc1f2722',
    messagingSenderId: '995049274759',
    projectId: 'fir-flutterdemo-458a6',
    storageBucket: 'fir-flutterdemo-458a6.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzRMiWNlkI4LOpryTH9ZptS1cTy1Jp3kA',
    appId: '1:995049274759:ios:cde547b15a0fbafc1f2722',
    messagingSenderId: '995049274759',
    projectId: 'fir-flutterdemo-458a6',
    storageBucket: 'fir-flutterdemo-458a6.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlV12QTttOP-WWvd9cYos1uvaSdKe_-p0',
    appId: '1:995049274759:web:4c57674500e08ca31f2722',
    messagingSenderId: '995049274759',
    projectId: 'fir-flutterdemo-458a6',
    authDomain: 'fir-flutterdemo-458a6.firebaseapp.com',
    storageBucket: 'fir-flutterdemo-458a6.appspot.com',
    measurementId: 'G-LX07H0ZYZC',
  );
}
